checks:
  - lidarr:
      source:
          type: github
          owner: Lidarr
          repo: Lidarr
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          template: github-discord
        - type: console
          template: github-discord
      meta:
        name: "Lidarr"
      period: 15s
      debug: true
  - varken:
      source:
          type: docker-hub
          namespace: boerderij
          repository: varken
          tag: develop
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          template: "New version of `${docker_hub__image}` pushed ${docker_hub__last_updated}."
        - type: console
      period: 20s
      debug: true
  - plex:
      source:
          type: docker-hub
          namespace: linuxserver
          repository: plex
          tag: latest
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          template: "New version of Plex pushed ${docker_hub__last_updated}. Get it [here](${meta__plex_url})"
      meta:
        plex_url: ${PYREMINDER_PLEX_URL}
      period: 20s
      debug: true
  - telegraf:
      source:
          type: docker-hub
          repository: telegraf
          tag: latest
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
        - type: console
      meta:
        name: "Telegraf"
      period: 20s
      debug: true
  - portainer:
      source:
          type: docker-hub
          namespace: portainer
          repository: portainer-ce
          tag: latest
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          template: docker-hub-discord
      meta:
        name: "Portainer"
      period: 20s
      debug: true

templates:
  github-discord: |
    Version ${github__tag} of ${meta__name} has been released! Download now!!!
    get it [here](${github__url})
    brought to you via check ${check__name}
  docker-hub-discord: |
    Version $docker_hub__version of $meta__name was released ${docker_hub__last_updated}!
    Get it by pulling the latest version of `${docker_hub__image}`
