checks:
  - plex:
      source:
        type: docker-hub
        namespace: linuxserver
        repository: plex
        tag: latest
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          color: 1ABC9C
          template: "New version of Plex pushed ${docker_hub__last_updated}. Get it [here](${meta__plex_url})"
      meta:
        plex_url: ${PYREMINDER_PLEX_URL}
      period: 1d
  - sonarr-apt:
      source:
        type: apt
        url: https://apt.sonarr.tv/debian
        component: main
        dist: jessie
        package: sonarr
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          template: "Version $apt__version of sonarr has been released."
      period: 30s
      debug: true