checks:
  - plex:
      source:
        type: get-request
        url: https://plex.tv/api/downloads/5.json
        parser: json
        parseKey: computer.Linux.version
      destinations:
        - type: console
          template: "New version of Plex released: ${get_request__text}"
      period: 1d
  - sonarr-apt:
      source:
        type: apt
        url: https://apt.sonarr.tv/debian
        component: main
        dist: jessie
        package: sonarr
      destinations:
        - type: discord
          webhookURL: ${PYREMINDER_DISCORD_WEBHOOK_URL}
          template: "Version $apt__version of sonarr has been released."
      period: 30s
      debug: true
